node:
  id: P1

sensors:
  - id: C
    type: ds18b20
    address: 28-00000048b650

  - id: W
    type: ds18b20
    address: 28-000000484442

  - id: K
    type: ds18b20
    address: 28-000000c8e589

  - id: X
    type: ds18b20
    address: 28-000000491730

  - id: THP01
    type: bme280
    bus: 1
    address: 0x76
